### ISSUE TITLE
本仓库的内容似乎被拿来卖课了

### ISSUE THREAD

**Issue by FunnySaltyFish** [milklabdev/jetpack-compose-book#291]
今天刷到一篇[推广文章](https://mp.weixin.qq.com/s/DM6RKqPFVVDkSNRs4UNxcw)，里面出现的所谓`附赠一套compose从入门到实战手册`内容正是此docs内容，只是被做成了pdf版本。
*此issue仅指出这一客观事实，不表述任何主观意见。如无意占据了issue公共空间，本人将第一时间删除。*

**Comment by Nthily** [comment]
感谢发现，暂时将此项目协议更改为 [CC BY-NC 2.0)](https://creativecommons.org/licenses/by-nc/2.0/deed.zh)
