### ISSUE TITLE
网站挂了

### ISSUE THREAD

**Issue by Goooler** [milklabdev/jetpack-compose-book#295]
如题，难道是因为 https://github.com/milklabdev/jetpack-compose-book/pull/294#discussion_r827600230 ？

**Comment by Nthily** [comment]
不需要给 main 分支提交东西我忘记了，那个是之前的文档备份
另外：测试了一下， nodejs 16.x 会报错，不知道什么原因

**Comment by Goooler** [comment]
啊这
