### ISSUE TITLE
图片链接挂了

### ISSUE THREAD

**Issue by Watermelon02** [milklabdev/jetpack-compose-book#302]

**Comment by Nthily** [comment]
具体是哪一章的？

**Comment by Watermelon02** [comment]
tutorial.mdx 这一章

**Comment by Nthily** [comment]
![image](https://user-images.githubusercontent.com/31311826/164243675-f6abc97c-ff08-4f07-8846-ab99e3436776.png)
我这里显示是好的。。。提醒你一下，这个网站服务器不在国内，是 github 提供的，直连也许有些问题
